name: Build and deploy documentation
on: [push]
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: schlessera/caliphper
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/